# Screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Shapes
SHAPE_LINE_WIDTH = 2
SHAPE_COLOR = "white"

# Bullet
BULLET_RADIUS = 5

# Asteroid
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player
PLAYER_RADIUS = 20
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_SHOOT_SPEED = 500
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
